services:
  mysql:
    image: mysql:latest
    container_name: ticketing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: events
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql:rw